### ISSUE TITLE
Add speed at or below restrictions

### ISSUE THREAD

**Issue by svalencia014** [mmp/vice#241] opened 2024-06-04 23:22 UTC
Currently, Vice does not support adding restrictions for crossing fixes at or below a certain speed. A good portion of the SIDs out of DCA include maximum speed restrctions, and it would help add some realistic performance over just assigning the max speed as the fix's speed restrction

TLDR: add /sXXX+ or /sXXX-

**Comment by mmp** [comment] 2024-06-04 23:37
Duplicate of #46...

**Closed by mmp** 2024-06-04 23:37 UTC
