### ISSUE TITLE
Range shown as a float in DCB.

### ISSUE THREAD

**Issue by checkandmate1** [mmp/vice#51] opened 2024-03-15 19:51 UTC
The `RANGE` DCB button shows the range as a float. Not an int. The RANGE in the SSA Filter displays an int and works as intended

**Comment by mmp** [comment] 2024-03-16 11:36
Fixed in 93e13d8daa363c1ab5f1471de54fc2f998061034

(The broader issue was that `PreferenceSet` stores the range as a `float32` and only recently as of 898d9adc11ff63865635729e209ec96d2472e8f7 do we enforce that it only take on integer values. So the problem is that in users' saved configurations, they may have non-integer values stored for range. If we changed `Range` in `PreferenceSet` to be an `int`, then the JSON parsing code would issue an error when parsing them ("that isn't an int") and vice would end up throwing away their saved configs and making them start from scratch.

So... `Range` is still a `float32` but at least `STARSPreferenceSet` `Activate` makes sure that it's an integer value and then the spinner keeps it an int. I'd missed the case of zooming with the scrollwheel though...

**Closed** 2024-03-16 11:35 UTC
Labels: bug, STARS
